// <auto-generated />
using System;
using DOAN52.Authentication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DOAN52.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DOAN52.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    //b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DOAN52.Models.QuanLyPhienBan", b =>
                {
                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("PhienBan")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.ToTable("QuanLyPhienBan","nhutero5_utehy");
                });

            modelBuilder.Entity("DOAN52.Models.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("token_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnName("expiry_date")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .HasColumnName("token")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("user_id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("DOAN52.Models.TblBacLuong", b =>
                {
                    b.Property<long>("MaBac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<double?>("HeSoBacLg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NhomBac")
                        .HasColumnType("ntext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenBac")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaBac");

                    b.ToTable("tblBacLuong");
                });

            modelBuilder.Entity("DOAN52.Models.TblBoMonTrungTam", b =>
                {
                    b.Property<string>("MaBmtt")
                        .HasColumnName("MaBMTT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("DiaChi")
                        .HasColumnType("ntext");

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PhanLoai")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongNhanSu")
                        .HasColumnType("int");

                    b.Property<string>("TenBmtt")
                        .HasColumnName("TenBMTT")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("MaBmtt");

                    b.HasIndex("MaPk");

                    b.ToTable("tblBoMonTrungTam");
                });

            modelBuilder.Entity("DOAN52.Models.TblCanBoGiangVien", b =>
                {
                    b.Property<string>("MaCbgv")
                        .HasColumnName("MaCBGV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("AiCap")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ChucDanh")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Cmnd")
                        .HasColumnName("CMND")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("Email")
                        .HasColumnType("ntext");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("KinhNghiem")
                        .HasColumnType("ntext");

                    b.Property<long?>("MaBac")
                        .HasColumnType("bigint");

                    b.Property<string>("MaBmtt")
                        .HasColumnName("MaBMTT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<long?>("MaKtkl")
                        .HasColumnName("MaKTKL")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaNgach")
                        .HasColumnType("bigint");

                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<long?>("MaTdhv")
                        .HasColumnName("MaTDHV")
                        .HasColumnType("bigint");

                    b.Property<string>("MatKhau")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TonGiao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TrinhDo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaCbgv");

                    b.HasIndex("MaBac");

                    b.HasIndex("MaBmtt");

                    b.HasIndex("MaKtkl");

                    b.HasIndex("MaNgach");

                    b.HasIndex("MaPk");

                    b.HasIndex("MaTdhv");

                    b.ToTable("tblCanBoGiangVien");
                });

            modelBuilder.Entity("DOAN52.Models.TblChiTietPhieuThu", b =>
                {
                    b.Property<long>("MaChiTietPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<int?>("HoaDonDienTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<long?>("MaKhoanNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaPhieuThu")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("numeric(18, 0)");

                    b.HasKey("MaChiTietPhieuThu");

                    b.ToTable("tblChiTietPhieuThu");
                });

            modelBuilder.Entity("DOAN52.Models.TblChuongTrinhDaoTao", b =>
                {
                    b.Property<string>("MaCtdt")
                        .HasColumnName("MaCTDT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("MaBmtt")
                        .HasColumnName("MaBMTT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaNganh")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("NamTs")
                        .HasColumnName("NamTS")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("SoTinChi")
                        .HasColumnType("float");

                    b.Property<string>("TenCtdt")
                        .HasColumnName("TenCTDT")
                        .HasColumnType("ntext");

                    b.HasKey("MaCtdt");

                    b.ToTable("tblChuongTrinhDaoTao");
                });

            modelBuilder.Entity("DOAN52.Models.TblChuongTrinhDaoTaoChiTiet", b =>
                {
                    b.Property<string>("MaCtdt")
                        .HasColumnName("MaCTDT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SoTt")
                        .HasColumnName("SoTT")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MaCtdt");

                    b.ToTable("tblChuongTrinhDaoTaoChiTiet");
                });

            modelBuilder.Entity("DOAN52.Models.TblDiemHocPhan", b =>
                {
                    b.Property<long>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("DiemThanhPhan")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<double?>("HeSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((1.0))");

                    b.Property<int?>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaSv")
                        .HasColumnName("MaSV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SoLanHoc")
                        .HasColumnType("int");

                    b.Property<int?>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<double?>("SoTinChi")
                        .HasColumnType("float");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrungBinh")
                        .HasColumnType("int");

                    b.Property<int?>("TotNghiep")
                        .HasColumnType("int");

                    b.HasKey("MaDiem");

                    b.ToTable("tblDiemHocPhan");
                });

            modelBuilder.Entity("DOAN52.Models.TblDiemHocPhanChiTiet", b =>
                {
                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("MaSv")
                        .HasColumnName("MaSV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("DiemThanhPhan")
                        .HasColumnType("text");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("HocKy")
                        .HasColumnType("int");

                    b.Property<int?>("KhaoSat")
                        .HasColumnType("int");

                    b.Property<int?>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiDay")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("ThuTu", "MaSv", "MaHp");

                    b.ToTable("tblDiemHocPhanChiTiet");
                });

            modelBuilder.Entity("DOAN52.Models.TblDinhMucHocPhi", b =>
                {
                    b.Property<long>("MaDmhp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaDMHP")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("HocKy")
                        .HasColumnType("int");

                    b.Property<decimal?>("HocPhiHocKy")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("HocPhiThang")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("HocPhiTinChi")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("HocPhiTinChiLt")
                        .HasColumnName("HocPhiTinChiLT")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("HocPhiTinChiTh")
                        .HasColumnName("HocPhiTinChiTH")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("MaKhoanThu")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaLop")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<int?>("NamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("QuyetDinh")
                        .HasColumnType("ntext");

                    b.Property<int?>("TinhChat")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDmhp");

                    b.ToTable("tblDinhMucHocPhi");
                });

            modelBuilder.Entity("DOAN52.Models.TblDkgiangDay", b =>
                {
                    b.Property<long>("MaDkgd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaDKGD")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("MaCbgv")
                        .HasColumnName("MaCBGV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayDk")
                        .HasColumnName("NgayDK")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.HasKey("MaDkgd");

                    b.HasIndex("MaCbgv");

                    b.HasIndex("MaHp");

                    b.ToTable("tblDKGiangDay");
                });

            modelBuilder.Entity("DOAN52.Models.TblGiaoVienChuNhiem", b =>
                {
                    b.Property<long>("MaGvcn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaGVCN")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BatDau")
                        .HasColumnType("datetime");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("HieuLuc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("MaCbgv")
                        .HasColumnName("MaCBGV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaLop")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaGvcn");

                    b.HasIndex("MaCbgv");

                    b.ToTable("tblGiaoVienChuNhiem");
                });

            modelBuilder.Entity("DOAN52.Models.TblHocPhan", b =>
                {
                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("DiemThanhPhan")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<double?>("HeSo")
                        .HasColumnType("float");

                    b.Property<int?>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaBmtt")
                        .HasColumnName("MaBMTT")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("NganhApDung")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<double?>("SoTinChi")
                        .HasColumnType("float");

                    b.Property<double?>("SoTinChiLt")
                        .HasColumnName("SoTinChiLT")
                        .HasColumnType("float");

                    b.Property<double?>("SoTinChiTh")
                        .HasColumnName("SoTinChiTH")
                        .HasColumnType("float");

                    b.Property<string>("TenHocPhan")
                        .HasColumnType("ntext");

                    b.Property<int?>("TinhChat")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrungBinh")
                        .HasColumnType("int");

                    b.Property<int?>("TotNghiep")
                        .HasColumnType("int");

                    b.HasKey("MaHp");

                    b.HasIndex("MaPk");

                    b.ToTable("tblHocPhan");
                });

            modelBuilder.Entity("DOAN52.Models.TblHopDongLd", b =>
                {
                    b.Property<long>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaHD")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("LoaiHd")
                        .HasColumnName("LoaiHD")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaCbgv")
                        .HasColumnName("MaCBGV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime");

                    b.HasKey("MaHd");

                    b.ToTable("tblHopDongLD");
                });

            modelBuilder.Entity("DOAN52.Models.TblKhenThuongKiLuat", b =>
                {
                    b.Property<long>("MaKtkl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaKTKL")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("LyDo")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnName("NgayKT")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<string>("TenKtkl")
                        .HasColumnName("TenKTKL")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaKtkl");

                    b.ToTable("tblKhenThuongKiLuat");
                });

            modelBuilder.Entity("DOAN52.Models.TblKhoanThu", b =>
                {
                    b.Property<string>("MaKhoanThu")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<int?>("HoaDonDienTu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TinhChat")
                        .HasColumnType("int");

                    b.HasKey("MaKhoanThu");

                    b.ToTable("tblKhoanThu");
                });

            modelBuilder.Entity("DOAN52.Models.TblLophoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("He")
                        .HasColumnType("int");

                    b.Property<string>("MaKhoaQuanLy")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaNganhHoc")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayNhapHoc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NienKhoa")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("TrinhDo")
                        .HasColumnType("int");

                    b.HasKey("MaLop");

                    b.ToTable("tblLophoc");
                });

            modelBuilder.Entity("DOAN52.Models.TblLuong", b =>
                {
                    b.Property<long>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<int?>("LuongCb")
                        .HasColumnName("LuongCB")
                        .HasColumnType("int");

                    b.Property<int?>("LuongPc")
                        .HasColumnName("LuongPC")
                        .HasColumnType("int");

                    b.Property<long?>("MaBac")
                        .HasColumnType("bigint");

                    b.Property<int?>("MucLuong")
                        .HasColumnType("int");

                    b.Property<string>("NgayNhan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("NgayTang")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaBac");

                    b.ToTable("tblLuong");
                });

            modelBuilder.Entity("DOAN52.Models.TblLyLichGv", b =>
                {
                    b.Property<long>("MaLl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaLL")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext");

                    b.Property<string>("LinkBaiBao")
                        .HasColumnType("ntext");

                    b.Property<string>("LoaiLl")
                        .HasColumnName("LoaiLL")
                        .HasColumnType("ntext");

                    b.Property<string>("MaCbgv")
                        .HasColumnName("MaCBGV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenLl")
                        .HasColumnName("TenLL")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaLl");

                    b.HasIndex("MaCbgv");

                    b.ToTable("tblLyLichGV");
                });

            modelBuilder.Entity("DOAN52.Models.TblNgachCongChuc", b =>
                {
                    b.Property<long>("MaNgach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<string>("MaSo")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenNgach")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaNgach");

                    b.ToTable("tblNgachCongChuc");
                });

            modelBuilder.Entity("DOAN52.Models.TblNganHang", b =>
                {
                    b.Property<string>("MaNganHang")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("text");

                    b.Property<string>("NgayTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("MaNganHang");

                    b.ToTable("tblNganHang");
                });

            modelBuilder.Entity("DOAN52.Models.TblNganhDaoTao", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("He")
                        .HasColumnType("int");

                    b.Property<string>("MaBmtt")
                        .HasColumnName("MaBMTT")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaNganhTs")
                        .HasColumnName("MaNganhTS")
                        .HasColumnType("ntext");

                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("NamTs")
                        .HasColumnName("NamTS")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SoThang")
                        .HasColumnType("int");

                    b.Property<double?>("SoTinChi")
                        .HasColumnType("float");

                    b.Property<string>("TenNganh")
                        .HasColumnType("ntext");

                    b.Property<int?>("TrinhDo")
                        .HasColumnType("int");

                    b.HasKey("MaNganh");

                    b.ToTable("tblNganhDaoTao");
                });

            modelBuilder.Entity("DOAN52.Models.TblPhieuThu", b =>
                {
                    b.Property<long>("MaPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int?>("HoaDonDienTu")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaNguoiThu")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<int?>("NamTaiKhoa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NguoiThu")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SoHieu")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("numeric(18, 0)");

                    b.HasKey("MaPhieuThu");

                    b.ToTable("tblPhieuThu");
                });

            modelBuilder.Entity("DOAN52.Models.TblPhongKhoa", b =>
                {
                    b.Property<string>("MaPk")
                        .HasColumnName("MaPK")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("DiaChi")
                        .HasColumnType("ntext");

                    b.Property<string>("DienThoai")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PhanLoai")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongNhanSu")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongKhoa")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Webiste")
                        .HasColumnType("ntext");

                    b.HasKey("MaPk");

                    b.ToTable("tblPhongKhoa");
                });

            modelBuilder.Entity("DOAN52.Models.TblQuanLyPhienBan", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDung")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<string>("PhienBan")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.ToTable("tblQuanLyPhienBan","nhutero5_utehy");
                });

            modelBuilder.Entity("DOAN52.Models.TblSinhVienLopHoc", b =>
                {
                    b.Property<long>("MaSvlh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaSVLH")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int?>("HoatDong")
                        .HasColumnType("int");

                    b.Property<string>("MaLop")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaSv")
                        .HasColumnName("MaSV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayVaoLop")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaSvlh");

                    b.ToTable("tblSinhVienLopHoc");
                });

            modelBuilder.Entity("DOAN52.Models.TblSinhvien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasColumnName("MaSV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Anh")
                        .HasColumnType("ntext");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("Email")
                        .HasColumnType("ntext");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("SoDinhDanh")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSv");

                    b.ToTable("tblSinhvien");
                });

            modelBuilder.Entity("DOAN52.Models.TblSoGhiNoSinhVien", b =>
                {
                    b.Property<long>("MaKhoanNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BatDau")
                        .HasColumnType("datetime");

                    b.Property<int?>("ChonSan")
                        .HasColumnType("int");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("KetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("MaHp")
                        .HasColumnName("MaHP")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaKhoanThu")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaSv")
                        .IsRequired()
                        .HasColumnName("MaSV")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("NamTaiKhoa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThu")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SoTienCanThu")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("SoTienDaThu")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MaKhoanNo");

                    b.ToTable("tblSoGhiNoSinhVien");
                });

            modelBuilder.Entity("DOAN52.Models.TblTrinhDoHocVan", b =>
                {
                    b.Property<long>("MaTdhv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaTDHV")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChungChi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ChuyenNganhDaoTao")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DonViCt")
                        .HasColumnName("DonViCT")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NamTotNghiêp")
                        .HasColumnType("datetime");

                    b.Property<string>("SoNamDay")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<string>("TdngoaiNgu")
                        .HasColumnName("TDNgoaiNgu")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TdtinHoc")
                        .HasColumnName("TDTinHoc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TenHocVan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("MaTdhv");

                    b.ToTable("tblTrinhDoHocVan");
                });

            modelBuilder.Entity("DOAN52.Models.TblUyNhiemThu", b =>
                {
                    b.Property<long>("MaUnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaUNT")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BatDau")
                        .HasColumnType("datetime");

                    b.Property<string>("Dp1")
                        .HasColumnName("DP1")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp2")
                        .HasColumnName("DP2")
                        .HasColumnType("ntext");

                    b.Property<string>("Dp3")
                        .HasColumnName("DP3")
                        .HasColumnType("ntext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("KetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MaKhoanThu")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaNganHang")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("MaUnt");

                    b.ToTable("tblUyNhiemThu");
                });

            modelBuilder.Entity("DOAN52.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Diachi")
                        .HasColumnName("diachi")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Gioitinh")
                        .HasColumnName("gioitinh")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Hoten")
                        .HasColumnName("hoten")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ImageUrl")
                        .HasColumnName("image_url")
                        .HasColumnType("varchar(300)")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<string>("Matkhau")
                        .HasColumnName("matkhau")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnName("ngaysinh")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Taikhoan")
                        .HasColumnName("taikhoan")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DOAN52.Models.RefreshToken", b =>
                {
                    b.HasOne("DOAN52.Models.User", "User")
                        .WithMany("RefreshToken")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__RefreshTo__user___4F47C5E3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DOAN52.Models.TblBoMonTrungTam", b =>
                {
                    b.HasOne("DOAN52.Models.TblPhongKhoa", "MaPkNavigation")
                        .WithMany("TblBoMonTrungTam")
                        .HasForeignKey("MaPk")
                        .HasConstraintName("FK_tblBoMonTrungTam_tblPhongKhoa");
                });

            modelBuilder.Entity("DOAN52.Models.TblCanBoGiangVien", b =>
                {
                    b.HasOne("DOAN52.Models.TblBacLuong", "MaBacNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaBac")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblBacLuong");

                    b.HasOne("DOAN52.Models.TblBoMonTrungTam", "MaBmttNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaBmtt")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblBoMonTrungTam");

                    b.HasOne("DOAN52.Models.TblKhenThuongKiLuat", "MaKtklNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaKtkl")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblKhenThuongKiLuat");

                    b.HasOne("DOAN52.Models.TblNgachCongChuc", "MaNgachNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaNgach")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblNgachCongChuc");

                    b.HasOne("DOAN52.Models.TblPhongKhoa", "MaPkNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaPk")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblPhongKhoa");

                    b.HasOne("DOAN52.Models.TblTrinhDoHocVan", "MaTdhvNavigation")
                        .WithMany("TblCanBoGiangVien")
                        .HasForeignKey("MaTdhv")
                        .HasConstraintName("FK_tblCanBoGiangVien_tblTrinhDoHocVan");
                });

            modelBuilder.Entity("DOAN52.Models.TblDkgiangDay", b =>
                {
                    b.HasOne("DOAN52.Models.TblCanBoGiangVien", "MaCbgvNavigation")
                        .WithMany("TblDkgiangDay")
                        .HasForeignKey("MaCbgv")
                        .HasConstraintName("FK_tblDKGiangDay_tblCanBoGiangVien");

                    b.HasOne("DOAN52.Models.TblHocPhan", "MaHpNavigation")
                        .WithMany("TblDkgiangDay")
                        .HasForeignKey("MaHp")
                        .HasConstraintName("FK_tblDKGiangDay_tblHocPhan");
                });

            modelBuilder.Entity("DOAN52.Models.TblGiaoVienChuNhiem", b =>
                {
                    b.HasOne("DOAN52.Models.TblCanBoGiangVien", "MaCbgvNavigation")
                        .WithMany("TblGiaoVienChuNhiem")
                        .HasForeignKey("MaCbgv")
                        .HasConstraintName("FK_tblGiaoVienChuNhiem_tblCanBoGiangVien");
                });

            modelBuilder.Entity("DOAN52.Models.TblHocPhan", b =>
                {
                    b.HasOne("DOAN52.Models.TblPhongKhoa", "MaPkNavigation")
                        .WithMany("TblHocPhan")
                        .HasForeignKey("MaPk")
                        .HasConstraintName("FK_tblHocPhan_tblPhongKhoa");
                });

            modelBuilder.Entity("DOAN52.Models.TblLuong", b =>
                {
                    b.HasOne("DOAN52.Models.TblBacLuong", "MaBacNavigation")
                        .WithMany("TblLuong")
                        .HasForeignKey("MaBac")
                        .HasConstraintName("FK_tblLuong_tblBacLuong");
                });

            modelBuilder.Entity("DOAN52.Models.TblLyLichGv", b =>
                {
                    b.HasOne("DOAN52.Models.TblCanBoGiangVien", "MaCbgvNavigation")
                        .WithMany("TblLyLichGv")
                        .HasForeignKey("MaCbgv")
                        .HasConstraintName("FK_tblLyLichGV_tblCanBoGiangVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DOAN52.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DOAN52.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOAN52.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DOAN52.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
